global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Markup;
global using Microsoft.Extensions.Logging;
global using Solution.DesktopApp.ViewModels;
global using Solution.DesktopApp.Configurations;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using System.Reflection;
global using Solution.Database;